name: pr-mac

on:
  pull_request

jobs:
  pr-mac:
    name: pr-mac
    runs-on: macos-11
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm@^7

      - name: Install dependencies
        run: pnpm install

      - name: Packing for mac
        run: |
          rm -rf ./.github
          npm run pack:mac
          npm run pack:mac-arm

      - name: Create zip package
        run: |
          npm run build:mac-zip
          npm run build:mac-arm-zip
          
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: pr-artifacts
          path: './dist/installers/*.*'
